{"name": "test_ue_ip", "status": "failed", "statusDetails": {"message": "AssertionError: can not get ue ip!\nassert False", "trace": "ue_ip = False\n\n    def test_ue_ip(ue_ip):\n>       assert ue_ip, \"can not get ue ip!\"\nE       AssertionError: can not get ue ip!\nE       assert False\n\ntest_001_pdu_establishment.py:51: AssertionError"}, "attachments": [{"name": "log", "source": "a5599899-0c7b-4b14-bd83-dd43a054b138-attachment.txt", "type": "text/plain"}], "start": 1566874060580, "stop": 1566874060580, "uuid": "bf7a340b-0a80-418d-9d42-b452c9923e1c", "historyId": "575efd220e11ac213a6fae93d178ce65", "testCaseId": "ea9e49c52440a3ab13f473cccaa01fbc", "fullName": "test_001_pdu_establishment#test_ue_ip", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_001_pdu_establishment"}, {"name": "subSuite"}, {"name": "host", "value": "ubuntu18"}, {"name": "thread", "value": "17389-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_001_pdu_establishment"}]}