{"name": "test_ue_ip", "status": "failed", "statusDetails": {"message": "AssertionError: can not get ue ip!\nassert False", "trace": "ue_ip = False\n\n    def test_ue_ip(ue_ip):\n>       assert ue_ip, \"can not get ue ip!\"\nE       AssertionError: can not get ue ip!\nE       assert False\n\ntest_001_pdu_establishment.py:51: AssertionError"}, "attachments": [{"name": "log", "source": "e281b75c-6cbe-4c89-af9d-b11792e65a0c-attachment.txt", "type": "text/plain"}], "start": 1566891402776, "stop": 1566891402776, "uuid": "47c6fbdb-4198-4940-ae61-0c9cbe116c70", "historyId": "575efd220e11ac213a6fae93d178ce65", "testCaseId": "ea9e49c52440a3ab13f473cccaa01fbc", "fullName": "test_001_pdu_establishment#test_ue_ip", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_001_pdu_establishment"}, {"name": "subSuite"}, {"name": "host", "value": "ubuntu18"}, {"name": "thread", "value": "5459-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_001_pdu_establishment"}]}