{"name": "test_ue_ip", "status": "failed", "statusDetails": {"message": "AssertionError: can not get ue ip!\nassert False", "trace": "ue_ip = False\n\n    def test_ue_ip(ue_ip):\n>       assert ue_ip, \"can not get ue ip!\"\nE       AssertionError: can not get ue ip!\nE       assert False\n\ntest_001_pdu_establishment.py:52: AssertionError"}, "attachments": [{"name": "log", "source": "430fe8ed-f265-47fd-8471-2d899d5ff45c-attachment.txt", "type": "text/plain"}], "start": 1566799420037, "stop": 1566799420038, "uuid": "46805b77-dc20-43c3-b9e8-8635b75e76e6", "historyId": "575efd220e11ac213a6fae93d178ce65", "testCaseId": "ea9e49c52440a3ab13f473cccaa01fbc", "fullName": "test_001_pdu_establishment#test_ue_ip", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_001_pdu_establishment"}, {"name": "subSuite"}, {"name": "host", "value": "ubuntu18"}, {"name": "thread", "value": "32686-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_001_pdu_establishment"}]}