{"name": "test_ue_ip", "status": "failed", "statusDetails": {"message": "AssertionError: can not get ue ip!\nassert False", "trace": "ue_ip = False\n\n    def test_ue_ip(ue_ip):\n>       assert ue_ip, \"can not get ue ip!\"\nE       AssertionError: can not get ue ip!\nE       assert False\n\ntest_01.py:52: AssertionError"}, "attachments": [{"name": "log", "source": "cc992a1a-0fff-45ad-be9e-a38e34f68731-attachment.txt", "type": "text/plain"}], "start": 1566726304157, "stop": 1566726304157, "uuid": "12f1c3e9-6dea-416c-9d19-c1d9510fe293", "historyId": "575efd220e11ac213a6fae93d178ce65", "testCaseId": "0d97a1fbc520f1a3b1c8d097be36d363", "fullName": "test_01#test_ue_ip", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite"}, {"name": "host", "value": "ubuntu18"}, {"name": "thread", "value": "23246-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}