{"name": "test_ue_ip", "status": "failed", "statusDetails": {"message": "AssertionError: can not get ue ip!\nassert False", "trace": "ue_ip = False\n\n    def test_ue_ip(ue_ip):\n>       assert ue_ip, \"can not get ue ip!\"\nE       AssertionError: can not get ue ip!\nE       assert False\n\ntest_001_pdu_establishment.py:51: AssertionError"}, "attachments": [{"name": "log", "source": "7bb9673d-e83b-42c8-8e3a-6d974865b129-attachment.txt", "type": "text/plain"}], "start": 1566875999505, "stop": 1566875999506, "uuid": "5a56b3d0-dc5d-4a86-b0d1-643320b38f7d", "historyId": "575efd220e11ac213a6fae93d178ce65", "testCaseId": "ea9e49c52440a3ab13f473cccaa01fbc", "fullName": "test_001_pdu_establishment#test_ue_ip", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_001_pdu_establishment"}, {"name": "subSuite"}, {"name": "host", "value": "ubuntu18"}, {"name": "thread", "value": "24145-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_001_pdu_establishment"}]}